### ISSUE TITLE
移动端开发

### ISSUE THREAD

**Issue by akai** [akai/notes#2]
# iOS

## The Notch

1. meta: `viewport-fit=cover`

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"> 
```

2. `safe-area.css`

```css
/* no safe area */
:root {
  --safe-area-inset-top: 0px;
  --safe-area-inset-bottom: 0px;
  --safe-area-inset-left: 0px;
  --safe-area-inset-right: 0px;
}

/* iOS 11.0-11.2 */
@supports (top: constant(safe-area-inset-top)) {
  :root {
    --safe-area-inset-top: constant(safe-area-inset-top);
    --safe-area-inset-bottom: constant(safe-area-inset-bottom);
    --safe-area-inset-left: constant(safe-area-inset-left);
    --safe-area-inset-right: constant(safe-area-inset-right);
  }
}

/* iOS 11.2+ */
@supports (top: env(safe-area-inset-top)) {
  :root {
    --safe-area-inset-top: env(safe-area-inset-top);
    --safe-area-inset-bottom: env(safe-area-inset-bottom);
    --safe-area-inset-left: env(safe-area-inset-left);
    --safe-area-inset-right: env(safe-area-inset-right);
  }
}
```

3. Usage

```css
.foo {
    bottom: 20px;
    bottom: calc(20px + var(--safe-area-inset-bottom));
}
```

- [Designing Websites for iPhone X](https://webkit.org/blog/7929/designing-websites-for-iphone-x/)
- [iPhone X layout features with CSS Environment variables](https://medium.com/@draganeror/iphone-x-layout-features-with-css-environment-variables-d57423433dec)
